### ISSUE TITLE
PHP_MSHUTDOWN_FUNCTION

### ISSUE THREAD

**Issue by longxinH** [tideways/php-profiler-extension#11]
php7-only verify
PHP_MSHUTDOWN_FUNCTION plus gc_collect_cycles = tw original gc_collect_cycles;

(gdb) bt
#0 0x00007ffff0312a1a in tw_span_create (category=0x7ffff031b17c "gc", 
category_len=2)
at /home/longxinhui/php-src/php70/ext/php-profiler-extension-php7-only/tideways.c:722
#1 0x00007ffff03196c0 in tw_gc_collect_cycles ()
at /home/longxinhui/php-src/php70/ext/php-profiler-extension-php7-only/tideways.c:3545
#2 0x0000000000ac4234 in shutdown_executor ()
at /home/longxinhui/Desktop/php70/php-7.0.1/Zend/zend_execute_API.c:352
#3 0x0000000000adf1d0 in zend_deactivate ()
at /home/longxinhui/Desktop/php70/php-7.0.1/Zend/zend.c:967
#4 0x0000000000a1e904 in php_request_shutdown (dummy=0x0)
at /home/longxinhui/Desktop/php70/php-7.0.1/main/main.c:1810
#5 0x0000000000baffae in do_cli (argc=2, argv=0x14f78d0)
at /home/longxinhui/Desktop/php70/php-7.0.1/sapi/cli/php_cli.c:1142
#6 0x0000000000bb0958 in main (argc=2, argv=0x14f78d0)
at /home/longxinhui/Desktop/php70/php-7.0.1/sapi/cli/php_cli.c:1345

**Comment by beberlei** [comment]
@longxinH please test the "php7" branch, the php7-only one is not current anymore.

**Comment by beberlei** [comment]
This should be fixed.
