### ISSUE TITLE
PECL release upload

### ISSUE THREAD

**Issue by carlwgeorge** [tideways/php-profiler-extension#16]
[This page](https://tideways.io/profiler/docs/setup/profiler-php-pecl-extension) mentions that this is a PECL extension, but I can't locate it on https://pecl.php.net.  Can releases be uploaded there?

**Comment by beberlei** [comment]
No sorry, not at the moment. You can get binaries from https://tideways.io/profiler/downloads that work with or without the Tideways service.

**Comment by glensc** [comment]
Let's try this again: https://github.com/tideways/php-xhprof-extension/issues/94
