### ISSUE TITLE
Latest master (v4.0.4) doesn't load

### ISSUE THREAD

**Issue by glenwong** [tideways/php-profiler-extension#18]
When I built from master and tested with php7, I got the following error:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/tideways.so' - /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/tideways.so: undefined symbol: zval_used_for_init in Unknown on line 0`

Syncing to the last release v4.0.3 and re-building worked.

**Comment by beberlei** [comment]
@glenwong which platform is that?

**Comment by glenwong** [comment]
It is a bit of an older version of Ubuntu...maybe that's the problem?:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise
```

Also I installed php7 via this repo: https://github.com/kasparsd/php-7-debian

**Comment by beberlei** [comment]
@glenwong we don't use the `zval_used_for_init` global variable anywhere, so that is odd. I think you might be building the extension wrong. Since you probably have two PHP versoins installed, maybe you call configure without `--with-php-config=path/to/php7/bin/php-config`

**Comment by glenwong** [comment]
Yeah, I did a search of the source code and also didn't see any references to zval_used_for_init. I have been using the configure path. That's how I got v4.0.3 to build. I just can't get v4.0.4 to build.

**Comment by beberlei** [comment]
I have linked this kind of mistake to a mismatch of debug/NTS/ZTS flags previously, this must be the case here.
