### ISSUE TITLE
Sampling with Tideways

### ISSUE THREAD

**Issue by joehoyle** [tideways/php-profiler-extension#26]
Is there any equivalent of `xhprof_sample_enable` in Tideways? Using `xhprof_enable` I can only get 1 level deep call stacks, which makes the data unusable for Flamegraphs and the like.

**Comment by beberlei** [comment]
@joehoyle no, we removed this functionality, because we didn't need it ourselves and it interfered with a refactoring. Sorry :-)

**Comment by rmccue** [comment]
@beberlei Would you be interested in re-adding it if there was community interest in supporting it?

**Comment by beberlei** [comment]
@rmccue to be honest no, since we have removed much of the code that makes the extension dynamically switch between callgraph and sampling modes and we really don't need the flamegraph sampling mode for our own use-case. I think it makes more sense to have a dedicated extension just for flamegraph profiling, but I haven't had time to work on one yet.

**Comment by rmccue** [comment]
Having dug into the code a bit (in an effort to port XHProf to PHP7 with sampling support), I agree that it's likely better as a separate extension. We're (@humanmade) quite interested in retaining sampling, so I'll investigate splitting it out into a separate extension that can work alongside the Tideways extension. :)

**Comment by Krinkle** [comment]
@rmccue We ran into the same issue when evaluating Tideways for PHP 7 at Wikimedia Foundation. See <https://phabricator.wikimedia.org/T176916>. Curious what your ended up doing, and whether we can collaborate or find a solution together.

**Comment by rmccue** [comment]
@Krinkle I ended up pinging Phacility directly about XHProf, and they pushed an experimental branch for PHP 7: https://github.com/phacility/xhprof/tree/experimental

We're definitely still interested in keeping XHProf + sampling for PHP 7 in an ongoing matter, so would love to collaborate if we can. This issue probably isn't the best place to discuss that, but feel free to email `ryan[at]hmn.md` if you want to chat :)
