### ISSUE TITLE
Use of php_url_parse_ex should be protected from NULL

### ISSUE THREAD

**Issue by glenwong** [tideways/php-profiler-extension#29]
It seems usages of php_url_parse_ex should deal with the possibility of NULL. I saw some crashes related to the url coming back as NULL and looking in the php src this is definitely a possibility.

**Comment by beberlei** [comment]
Thank you, that is a good pointer. Looking at the code of the method, it seems it will always return an url though, but php-src itself checks for == NULL as return value as well, so better be safe.
