### ISSUE TITLE
Error in tideways-daemon

### ISSUE THREAD

**Issue by KomaBeyond** [tideways/php-profiler-extension#40]
Ok, first i am use this in the alpinelinux. So i fllow the steps in "Other Linux" section. When i download the file of  "tideways-daemon_linux_amd64-1.2.5.tar.gz"  and then run by the command and there was an error occurred.
##### useradd command not found in alpinelinux, because we use adduser instead.
Ok, i changed the command by myself and run it again, another error occurred.
##### /usr/bin/tideways-daemon No such file 
Well, when i use this command 
```bash
ld /usr/bin/tideways-daemon
```
it return something like this:
##### 
/lib64/ld-linux-x86-64.so.2 (0x7fbbc0dc4000)
libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fbbc0dc4000)
libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fbbc0dc4000)
Error relocating /usr/bin/tideways-daemon: __fprintf_chk: symbol not found

So, how could i fix it?

**Comment by beberlei** [comment]
The "Other Linux" section still assumes, you are using a glibc based Linux. The daemon for Alpine is here:

https://s3-eu-west-1.amazonaws.com/tideways/daemon/1.5.3/tideways-daemon-v1.5.3-alpine.tar.gz

**Comment by beberlei** [comment]
Please write support@tideways.io for support questions in the future, this repository is just for the open source part of the PHP extension.
