### ISSUE TITLE
build failure when PDO is disabled

### ISSUE THREAD

**Issue by rcanavan** [tideways/php-profiler-extension#41]
the profiler fails to build if PHP has been build without PDO. We build PHP 7.1.6 with `--disable-all` and  `--without-pdo-sqlite -without-pdo-mysql  --without-pgsql  --without-pdo-pgsql`. `configure` should check that /php_pdo_driver.h exists, and any references to pdo should be #ifdef-ed out of tideways.c

```
php-profiler-extension/tideways.c:46:36: fatal error: ext/pdo/php_pdo_driver.h: No such file or directory
 #include "ext/pdo/php_pdo_driver.h"
                                    ^
```

**Comment by beberlei** [comment]
You are right, this can be improved

**Comment by beberlei** [comment]
Fixed.

**Comment by rcanavan** [comment]
tested, works for me. Thanks.
